name: github_actios_flaskapp
env:
  APP_NAME: "flaskapp"
  PACKAGE_NAME: "flask_package_ver_${{ github.sha }}"

on:
  push:
    branches: 
      - main

jobs: 
  test: 
    runs-on: ubuntu-latest 

    steps: 
    - name: Print hello message
      run: echo "Test passed successfully!"
    
    - name: Execute some commands 
      run: |
        echo "Hello message1"
        echo "Hello message2"
        echo "Application name is: ${{ env.APP_NAME }}"
    
    - name: list current folder 
      run: ls -la 

    - name: git clone my repo 
      uses: actions/checkout@v1

    - name: list current folder 2
      run: ls -la 
  
  deploy: 
    runs-on: ubuntu-latest
    needs: [test]
    env:
      VAR1: "this is job level variable 1"
      VAR2: "this is job level variable 2"
    
    steps: 
    - name: Print Hello message
      run: echo "Aloha from deploy"

    - name: testing job level variables 
      run: | 
        echo "VAR1 = ${{ env.VAR1 }}"
        echo "VAR2 = ${{ env.VAR2 }}"
        echo "VAR3 = $LOCAL_VAR"
      env: 
        LOCAL_VAR: "this is local variable"

    - name: Deployment package
      run: | 
        echo "Deployed package is: ${{ env.PACKAGE_NAME }}"
    
    - name: Testing aws command
      run: aws --version

    - name: Testing zip command 
      run: zip 
